language: node_js

sudo: false

node_js:
  - "node"

addons:
  apt:
    packages:
      - p7zip-full

env:
  global:
    - BASE_NAME=shariff-$TRAVIS_TAG

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  - provider: releases
    api_key:
      secure: "QK+97CEzaL5FwA09hs7II9PnBKn1KRUUOLtmGnIw83FiqI5dUtAfPxe0WuA9dwIVX9FKOtPacn5nSoPb0LVvWwdTxGN2DOnYrUW8pIsPGng1Z5kbD2feJdTIeXkVmKb8JYssq76L7O6SyXQbkrbYq6KmrjFH9bEEpGlcUOyKY+k="
    file:
      - $BASE_NAME.zip
      - $BASE_NAME.tar.gz
    skip_cleanup: true
    script: npm run build_zip
    on:
      repo: heiseonline/shariff
      tags: true
  - provider: npm
    email: npmjs@heise.de
    api_key:
      secure: "hbiJOthZutV4G+4FidwK4XfDPPNXgdwWMeWjaFJueFdNwm5ifwnRl4CbSjPSW1os+0qRNF6HRFJbeRcZllqqQQfCSJB0fqB3AWFiSqvXzw+aJgO83EzEIxKSAD70/R+HME+ZX/JopBvFDe4mrsWGZk92kY2R/BS986yktIKGjJk="
    skip_cleanup: true
    on:
      repo: heiseonline/shariff
      tags: true
